version: '3.8'

services:
  # Service pour la base de données MySQL
  taskdb:
    image: mysql:latest
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: taskdb
    ports:
      - "3306:3306"  # Le port 3306 de l'hôte est mappé au port 3306 du conteneur
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # Service pour le backend Spring Boot
  projectmanager_springboot:
    build:
      context: ./ProjectManager_springboot  # Si vous avez un Dockerfile dans le dossier backend
    container_name: projectmanager_springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://taskdb:3306/taskdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"  # Le port 8080 de l'hôte est mappé au port 8080 du conteneur
    depends_on:
      - taskdb
    networks:
      - app-network
    restart: always

  # Service pour le frontend Angular
  projectmanager_angular:
    build:
      context: ./projectmanager_angular  # Si vous avez un Dockerfile dans le dossier frontend
    container_name: projectmanager_angular
    ports:
      - "4200:80"  # Le port 4200 de l'hôte est mappé au port 80 du conteneur Nginx
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
